// ============================================================
// 本地开发 / 演示模式种子数据
// ============================================================

import type {
  DecisionAnswer,
  DecisionForm,
  DecisionOption,
  DecisionQuestion,
  DecisionResponse,
  Task,
  TaskUpdate,
} from '../types'

export const seedTasks: Task[] = [
  {
    id: 't-crash',
    title: 'iOS 启动崩溃热修复',
    description: '偶现启动 crash，排查原因为空指针，已提交热修补丁。',
    status: 'completed',
    priority: 'urgent',
    progress: 100,
    current_status: '已发布修复包，线上观测指标正常。',
    block_reason: '',
    start_date: '2026-03-01',
    expected_end_date: '2026-03-01',
    actual_end_date: '2026-03-01',
    is_interrupt_task: false,
    created_at: new Date(Date.now() - 24 * 36e5).toISOString(),
    updated_at: new Date(Date.now() - 20 * 36e5).toISOString(),
  },
  {
    id: 't-puzzle',
    title: '拼图关卡流转重构',
    description: '重构拼图结算流程，提升动画流畅度与连击反馈。',
    status: 'in_progress',
    priority: 'high',
    progress: 60,
    current_status: '连击计算逻辑开发中，等待产品确认道具中断规则。',
    block_reason: '',
    start_date: '2026-03-01',
    expected_end_date: '2026-03-05',
    actual_end_date: null,
    is_interrupt_task: false,
    created_at: new Date(Date.now() - 48 * 36e5).toISOString(),
    updated_at: new Date(Date.now() - 2 * 36e5).toISOString(),
  },
]

export const seedUpdates: TaskUpdate[] = [
  {
    id: 'u-crash-1',
    task_id: 't-crash',
    type: 'blocked',
    content: '线上出现紧急启动崩溃，排查符号表中。',
    old_expected_end_date: null,
    new_expected_end_date: null,
    created_at: new Date(Date.now() - 23 * 36e5).toISOString(),
    created_by: 'admin',
  },
  {
    id: 'u-crash-2',
    task_id: 't-crash',
    type: 'progress',
    content: '定位崩溃原因并完成修复。',
    old_expected_end_date: null,
    new_expected_end_date: null,
    created_at: new Date(Date.now() - 22 * 36e5).toISOString(),
    created_by: 'admin',
  },
  {
    id: 'u-crash-3',
    task_id: 't-crash',
    type: 'completed',
    content: '修复包已发布，观察无异常。',
    old_expected_end_date: null,
    new_expected_end_date: null,
    created_at: new Date(Date.now() - 21 * 36e5).toISOString(),
    created_by: 'admin',
  },
]

export const seedDecisionForms: DecisionForm[] = [
  {
    id: 'df-puzzle-1',
    slug: 'puzzle-retention-incentives',
    title: '拼图积分与完成激励：请确认产品决策',
    summary: '请逐题确认 D1～D10 关键产品决策；未覆盖的口径请写在补充说明。',
    source_document: '# 拼图积分与完成激励 PRD\n\n本功能旨在通过连击与 Hint 道具机制提升玩家的沉浸感与通关留存。\n\n## 待确认事项\n- D1: 连击计算与中断逻辑\n- D2: Hint 道具使用对连击的影响\n- D3: 连击重置时间窗口\n- D4: 连击阶梯奖励加成比例\n- D5: 首通双倍积分生效范围\n- D6: 道具自动消耗弹窗确认\n- D7: 积分排行榜刷新周期\n- D8: 离线模式积分缓存与防作弊\n- D9: 异常退出与重连连击恢复策略\n- D10: 其它细化规则按推荐方案统筹执行',
    status: 'open',
    created_by: 'decision-form-agent',
    created_at: new Date(Date.now() - 24 * 36e5).toISOString(),
    closed_at: null,
    updated_at: new Date(Date.now() - 24 * 36e5).toISOString(),
  },
]

export const seedDecisionQuestions: DecisionQuestion[] = [
  {
    id: 'dq-1',
    form_id: 'df-puzzle-1',
    code: 'D1',
    sort_order: 0,
    title: '连击如何累计和中断',
    context: '策划案未定义一次放置操作如何计数，需确认计数基准。',
    type: 'single_choice',
    required: true,
    allow_other: true,
    recommended_option_id: 'do-1-a',
    recommended_reason: '按竞品 5.0.21 源码确认后的事件口径，手感更连贯。',
    options: [],
  },
  {
    id: 'dq-2',
    form_id: 'df-puzzle-1',
    code: 'D2',
    sort_order: 1,
    title: 'Hint / 自动放置是否得分、是否中断连击',
    context: '使用辅助道具时的分数计算和连击策略。',
    type: 'single_choice',
    required: true,
    allow_other: true,
    recommended_option_id: 'do-2-b',
    recommended_reason: '道具正常得分但清零连击，既鼓励道具消耗又防止外挂刷分。',
    options: [],
  },
  {
    id: 'dq-3',
    form_id: 'df-puzzle-1',
    code: 'D3',
    sort_order: 2,
    title: '连击维持的时间窗口（Combo Timeout）',
    context: '放置成功后，连击计时条的有效衰减秒数。',
    type: 'single_choice',
    required: true,
    allow_other: true,
    recommended_option_id: 'do-3-b',
    recommended_reason: '4.5 秒给新手足够反应时间，同时保持紧凑节奏。',
    options: [],
  },
  {
    id: 'dq-4',
    form_id: 'df-puzzle-1',
    code: 'D4',
    sort_order: 3,
    title: '连击阶梯奖励加成范围',
    context: '高连击时额外积分倍率上限。',
    type: 'single_choice',
    required: true,
    allow_other: false,
    recommended_option_id: 'do-4-a',
    recommended_reason: '阶梯上限 2.0x 可平衡经济系统膨胀。',
    options: [],
  },
  {
    id: 'dq-5',
    form_id: 'df-puzzle-1',
    code: 'D5',
    sort_order: 4,
    title: '首通双倍积分生效模式',
    context: '玩家首次通关新关卡时的奖励计算。',
    type: 'single_choice',
    required: true,
    allow_other: true,
    recommended_option_id: 'do-5-a',
    recommended_reason: '首通按关卡最终结算总分做 2x 翻倍。',
    options: [],
  },
  {
    id: 'dq-6',
    form_id: 'df-puzzle-1',
    code: 'D6',
    sort_order: 5,
    title: 'Hint 道具不足时的购买确认弹窗',
    context: '玩家道具数为 0 时点击道具栏的行为。',
    type: 'single_choice',
    required: true,
    allow_other: true,
    recommended_option_id: 'do-6-a',
    recommended_reason: '直接呼出轻量快捷购买气泡，避免打断游戏心流。',
    options: [],
  },
  {
    id: 'dq-7',
    form_id: 'df-puzzle-1',
    code: 'D7',
    sort_order: 6,
    title: '积分周排行榜刷新与结算周期',
    context: '全服积分周榜的清榜时间点。',
    type: 'single_choice',
    required: true,
    allow_other: false,
    recommended_option_id: 'do-7-a',
    recommended_reason: '每周一 00:00 (Asia/Shanghai) 统一重置并发放奖励。',
    options: [],
  },
  {
    id: 'dq-8',
    form_id: 'df-puzzle-1',
    code: 'D8',
    sort_order: 7,
    title: '弱网与离线积分同步校验策略',
    context: '弱网环境下本地离线暂存的最大积分记录上限与签名验证。',
    type: 'single_choice',
    required: true,
    allow_other: true,
    recommended_option_id: 'do-8-a',
    recommended_reason: '本地最多缓存 20 关积分记录，带设备指纹签名，联网后批量同步。',
    options: [],
  },
  {
    id: 'dq-9',
    form_id: 'df-puzzle-1',
    code: 'D9',
    sort_order: 8,
    title: '异常崩溃退出后的连击状态恢复口径',
    context: '发生闪退或强退时，重新进入关卡是否保留连击数。',
    type: 'free_text',
    required: true,
    allow_other: false,
    recommended_option_id: null,
    recommended_reason: '崩溃恢复时保留关卡进度但清零当前实时连击计时器。',
    options: [],
  },
  {
    id: 'dq-10',
    form_id: 'df-puzzle-1',
    code: 'D10',
    sort_order: 9,
    title: '其余子规则确认（按推荐方案统筹执行）',
    context: '包含动画缓动曲线与震动反馈等未单列的通用口径。',
    type: 'confirmation',
    required: true,
    allow_other: false,
    recommended_option_id: null,
    recommended_reason: '按 PRD 推荐方案统一执行。',
    options: [],
  },
]

export const seedDecisionOptions: DecisionOption[] = [
  // D1
  {
    id: 'do-1-a',
    question_id: 'dq-1',
    code: 'A',
    label: '按竞品事件口径（连续成功放置计 Combo）',
    detail: '按竞品 5.0.21 源码确认后的事件口径，每次正确放置拼图块即计入 Combo。',
    sort_order: 0,
  },
  {
    id: 'do-1-b',
    question_id: 'dq-1',
    code: 'B',
    label: '按底层松手事件计数',
    detail: '每次松手放置拼图块即触发计数，放错直接清零。',
    sort_order: 1,
  },
  // D2
  {
    id: 'do-2-a',
    question_id: 'dq-2',
    code: 'A',
    label: 'Hint 正常得分并继续累加连击',
    detail: '鼓励道具使用，体验更爽快。',
    sort_order: 0,
  },
  {
    id: 'do-2-b',
    question_id: 'dq-2',
    code: 'B',
    label: 'Hint 正常得分，但清零连击',
    detail: '与竞品一致，避免使用道具刷高连击排行榜。',
    sort_order: 1,
  },
  {
    id: 'do-2-c',
    question_id: 'dq-2',
    code: 'C',
    label: 'Hint 不得分且清零连击',
    detail: '惩罚性规则，对玩家较为严苛。',
    sort_order: 2,
  },
  // D3
  {
    id: 'do-3-a',
    question_id: 'dq-3',
    code: 'A',
    label: '3.0 秒窗口',
    detail: '高难度紧凑节奏。',
    sort_order: 0,
  },
  {
    id: 'do-3-b',
    question_id: 'dq-3',
    code: 'B',
    label: '4.5 秒窗口',
    detail: '适中难度，兼顾思考与操作。',
    sort_order: 1,
  },
  {
    id: 'do-3-c',
    question_id: 'dq-3',
    code: 'C',
    label: '6.0 秒窗口',
    detail: '休闲宽松节奏。',
    sort_order: 2,
  },
  // D4
  {
    id: 'do-4-a',
    question_id: 'dq-4',
    code: 'A',
    label: '最高 2.0x 阶梯倍率（3~5连 1.2x，6~9连 1.5x，10+连 2.0x）',
    detail: '平衡经济系统数值。',
    sort_order: 0,
  },
  {
    id: 'do-4-b',
    question_id: 'dq-4',
    code: 'B',
    label: '最高 3.0x 阶梯倍率（刺激冲榜）',
    detail: '激励深度硬核玩家。',
    sort_order: 1,
  },
  // D5
  {
    id: 'do-5-a',
    question_id: 'dq-5',
    code: 'A',
    label: '关卡最终总分结算时全局 2x 翻倍',
    detail: '含基础分与连击加成后统一翻倍。',
    sort_order: 0,
  },
  {
    id: 'do-5-b',
    question_id: 'dq-5',
    code: 'B',
    label: '仅基础通关分翻倍，连击分不翻倍',
    detail: '控制首通溢出分数。',
    sort_order: 1,
  },
  // D6
  {
    id: 'do-6-a',
    question_id: 'dq-6',
    code: 'A',
    label: '气泡轻量弹窗，单点即买即用',
    detail: '无全屏遮罩，保持手感连贯。',
    sort_order: 0,
  },
  {
    id: 'do-6-b',
    question_id: 'dq-6',
    code: 'B',
    label: '标准模态对话框确认',
    detail: '二次确认防误触。',
    sort_order: 1,
  },
  // D7
  {
    id: 'do-7-a',
    question_id: 'dq-7',
    code: 'A',
    label: '每周一 00:00 (Asia/Shanghai)',
    detail: '与常规周活动对齐。',
    sort_order: 0,
  },
  {
    id: 'do-7-b',
    question_id: 'dq-7',
    code: 'B',
    label: '每周日 24:00 结束并锁定 1 小时结算',
    detail: '防结算并发。',
    sort_order: 1,
  },
  // D8
  {
    id: 'do-8-a',
    question_id: 'dq-8',
    code: 'A',
    label: '最多缓存 20 关，联网后批量上报',
    detail: '兼顾离线游玩与数据安全。',
    sort_order: 0,
  },
  {
    id: 'do-8-b',
    question_id: 'dq-8',
    code: 'B',
    label: '离线仅允许通关，积分不计入全服榜单',
    detail: '严格防作弊。',
    sort_order: 1,
  },
]

// 初始默认 0 份答卷（无预设硬编码姓名），供干净验收与填答
export const seedDecisionResponses: DecisionResponse[] = []
export const seedDecisionAnswers: DecisionAnswer[] = []

export function buildSeed(): {
  tasks: Task[]
  updates: TaskUpdate[]
  decisionForms: DecisionForm[]
  decisionQuestions: DecisionQuestion[]
  decisionOptions: DecisionOption[]
  decisionResponses: DecisionResponse[]
  decisionAnswers: DecisionAnswer[]
} {
  return {
    tasks: seedTasks,
    updates: seedUpdates,
    decisionForms: seedDecisionForms,
    decisionQuestions: seedDecisionQuestions,
    decisionOptions: seedDecisionOptions,
    decisionResponses: seedDecisionResponses,
    decisionAnswers: seedDecisionAnswers,
  }
}
